(() => {
  const catalog = window.CS_CATALOG;
  if (!catalog) return;
  catalog.checklists = catalog.checklists || {};

  const additions = [
    {id:'panini-intl-england-2026',sport:'Soccer',manufacturer:'Panini',year:'2026',name:'2026 Panini INTL England Soccer',shortName:'Panini INTL England 2026',sourceUrl:'https://www.beckett.com/news/2026-panini-intl-england-soccer-cards/',coverage:'base-complete',baseCount:20},
    {id:'panini-intl-france-2026',sport:'Soccer',manufacturer:'Panini',year:'2026',name:'2026 Panini INTL France Soccer',shortName:'Panini INTL France 2026',sourceUrl:'https://packaddx.com/checklists/sports/soccer/panini_soccer_2026_Panini_panini-intl-france',coverage:'base-complete',baseCount:20},
    {id:'panini-intl-germany-2026',sport:'Soccer',manufacturer:'Panini',year:'2026',name:'2026 Panini INTL Germany Soccer',shortName:'Panini INTL Germany 2026',sourceUrl:'https://www.beckett.com/news/2026-panini-intl-germany-soccer-checklist-and-details/',coverage:'base-complete',baseCount:20},
    {id:'panini-intl-mexico-2026',sport:'Soccer',manufacturer:'Panini',year:'2026',name:'2026 Panini INTL Mexico Soccer',shortName:'Panini INTL México 2026',sourceUrl:'https://www.checklistcenter.com/2026-panini-intl-mexico-soccer-card-checklist/',coverage:'base-complete',baseCount:20},

    {id:'topps-barcelona-collector-tin-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps FC Barcelona Collector Tin 2025/26',shortName:'Barcelona Collector Tin 25/26',sourceUrl:'https://es.topps.com/products/25-26-barcelona-collector-tin',checklistUrl:'https://cdn.shopify.com/s/files/1/0697/4249/3893/files/2025-26_FC_Barcelona_Collector_Tin_Checklist.pdf?v=1787910121',coverage:'full-checklist',baseCount:30},
    {id:'topps-man-city-collector-tin-2026-27',sport:'Soccer',manufacturer:'Topps',year:'2026/27',name:'Topps Manchester City Collector Tin 2026/27',shortName:'Man City Collector Tin 26/27',sourceUrl:'https://es.topps.com/products/topps-collector-tin-manchester-city-2026-27',checklistUrl:'https://cdn.shopify.com/s/files/1/0697/4249/3893/files/Manchester_City_Collector_Tin_Checklist.pdf?v=1789644750',coverage:'full-checklist',baseCount:29},

    {id:'topps-real-madrid-collector-tin-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps Real Madrid Collector Tin 2025/26',shortName:'Real Madrid Collector Tin 25/26',sourceUrl:'https://es.topps.com/products/2025-26-real-madrid-collector-tin',coverage:'collection'},
    {id:'topps-liverpool-collector-tin-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps Liverpool Collector Tin 2025/26',shortName:'Liverpool Collector Tin 25/26',sourceUrl:'https://es.topps.com/products/2025-26-liverpool-collector-tin',checklistUrl:'https://cdn.shopify.com/s/files/1/0697/4249/3893/files/2025-26_Liverpool_Collector_Tin_Checklist.pdf?v=1787911799',coverage:'collection'},
    {id:'topps-juventus-collector-tin-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps Juventus Collector Tin 2025/26',shortName:'Juventus Collector Tin 25/26',sourceUrl:'https://es.topps.com/products/2025-26-juventus-collector-tin',checklistUrl:'https://cdn.shopify.com/s/files/1/0697/4249/3893/files/25-26_Juventus_Collector_Tin_Checklist.pdf?v=1787910779',coverage:'collection'},
    {id:'topps-bayern-collector-tin-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps Bayern München Collector Tin 2025/26',shortName:'Bayern Collector Tin 25/26',sourceUrl:'https://es.topps.com/products/25-26-bayern-munchen-collector-tin',checklistUrl:'https://cdn.shopify.com/s/files/1/0697/4249/3893/files/25-26_Bayern_Munchen_Collector_Tin_Checklist.pdf?v=1787910787',coverage:'collection'},
    {id:'topps-celtic-collector-tin-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps Celtic FC Collector Tin 2025/26',shortName:'Celtic Collector Tin 25/26',sourceUrl:'https://es.topps.com/products/2025-26-celtic-fc-collector-tin',coverage:'collection'},
    {id:'topps-man-utd-collector-tin-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps Manchester United Collector Tin 2025/26',shortName:'Man United Collector Tin 25/26',sourceUrl:'https://in.topps.com/products/2025-26-manchester-united-collector-tin',coverage:'collection'},

    {id:'topps-arsenal-collector-tin-2026-27',sport:'Soccer',manufacturer:'Topps',year:'2026/27',name:'Topps Arsenal Collector Tin 2026/27',shortName:'Arsenal Collector Tin 26/27',sourceUrl:'https://www.topps.com/pages/football-club-collections',coverage:'collection'},
    {id:'topps-chelsea-collector-tin-2026-27',sport:'Soccer',manufacturer:'Topps',year:'2026/27',name:'Topps Chelsea Collector Tin 2026/27',shortName:'Chelsea Collector Tin 26/27',sourceUrl:'https://es.topps.com/products/topps-collector-tin-chelsea-2026-27',coverage:'collection'},
    {id:'topps-man-utd-collector-tin-2026-27',sport:'Soccer',manufacturer:'Topps',year:'2026/27',name:'Topps Manchester United Collector Tin 2026/27',shortName:'Man United Collector Tin 26/27',sourceUrl:'https://es.topps.com/products/topps-collector-tin-manchester-united-2026-27',coverage:'collection'},
    {id:'topps-inter-collector-tin-2026-27',sport:'Soccer',manufacturer:'Topps',year:'2026/27',name:'Topps Inter Collector Tin 2026/27',shortName:'Inter Collector Tin 26/27',sourceUrl:'https://www.topps.com/pages/football-club-collections',coverage:'collection'},
    {id:'topps-psg-collector-tin-2026-27',sport:'Soccer',manufacturer:'Topps',year:'2026/27',name:'Topps Paris Saint-Germain Collector Tin 2026/27',shortName:'PSG Collector Tin 26/27',sourceUrl:'https://www.topps.com/pages/football-club-collections',coverage:'collection'},

    {id:'topps-benfica-team-set-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps SL Benfica Team Set 2025/26',shortName:'Benfica Team Set 25/26',sourceUrl:'https://es.topps.com/pages/topps-team-set-sl-benfica',coverage:'collection'},
    {id:'topps-chelsea-team-set-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps Chelsea Team Set 2025/26',shortName:'Chelsea Team Set 25/26',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'},
    {id:'topps-atletico-team-set-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps Atlético de Madrid Team Set 2025/26',shortName:'Atlético Team Set 25/26',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'},
    {id:'topps-barcelona-forever-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps FC Barcelona Forever 2025/26',shortName:'Barcelona Forever 25/26',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'},

    {id:'topps-finest-ucc-2025-26',sport:'Soccer',manufacturer:'Topps',year:'2025/26',name:'Topps Finest UEFA Club Competitions 2025/26',shortName:'Finest UEFA 25/26',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'},
    {id:'panini-prizm-monopoly-world-cup-2026',sport:'Soccer',manufacturer:'Panini',year:'2026',name:'Panini Prizm Monopoly FIFA World Cup 2026',shortName:'Prizm Monopoly WC 2026',sourceUrl:'https://www.paniniamerica.net/checklist.html',coverage:'collection',baseCount:100},
    {id:'panini-select-la-liga-2024-25',sport:'Soccer',manufacturer:'Panini',year:'2024/25',name:'Panini Select LaLiga 2024/25',shortName:'Select LaLiga 24/25',sourceUrl:'https://www.paniniamerica.net/checklist.html',coverage:'collection'},
    {id:'panini-prizm-club-world-cup-2025',sport:'Soccer',manufacturer:'Panini',year:'2025',name:'Panini Prizm FIFA Club World Cup 2025',shortName:'Prizm Club World Cup 2025',sourceUrl:'https://www.paniniamerica.net/checklist.html',coverage:'collection'},

    {id:'topps-resurgence-football-2025',sport:'NFL',manufacturer:'Topps',year:'2025',name:'Topps Resurgence Football 2025',shortName:'Resurgence NFL 2025',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'},
    {id:'topps-flagship-football-2026',sport:'NFL',manufacturer:'Topps',year:'2026',name:'Topps Flagship Football 2026',shortName:'Flagship NFL 2026',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'},

    {id:'topps-holiday-baseball-2025',sport:'MLB',manufacturer:'Topps',year:'2025',name:'Topps Holiday Baseball 2025',shortName:'Holiday MLB 2025',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'},
    {id:'topps-update-baseball-2026',sport:'MLB',manufacturer:'Topps',year:'2026',name:'Topps Update Series Baseball 2026',shortName:'Update MLB 2026',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'},
    {id:'bowman-chrome-baseball-2026',sport:'MLB',manufacturer:'Topps',year:'2026',name:'Bowman Chrome Baseball 2026',shortName:'Bowman Chrome 2026',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'},
    {id:'topps-archives-snapshots-baseball-2021',sport:'MLB',manufacturer:'Topps',year:'2021',name:'Topps Archives Snapshots Baseball 2021',shortName:'Archives Snapshots MLB 2021',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'},

    {id:'topps-stadium-club-ufc-2026',sport:'UFC',manufacturer:'Topps',year:'2026',name:'Topps Stadium Club UFC 2026',shortName:'Stadium Club UFC 2026',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'},
    {id:'topps-premier-league-2026-27',sport:'Soccer',manufacturer:'Topps',year:'2026/27',name:'Topps Premier League 2026/27',shortName:'Premier League 26/27',sourceUrl:'https://www.topps.com/pages/checklists',coverage:'collection'}
  ];

  const existing = new Set(catalog.collections.map(c => c.id));
  additions.forEach(c => { if (!existing.has(c.id)) catalog.collections.push(c); });

  catalog.checklists['panini-intl-england-2026'] = [
    [1,'Harry Kane','England',0,'Base'],[2,'Trent Alexander-Arnold','England',0,'Base'],[3,'Declan Rice','England',0,'Base'],[4,'Jude Bellingham','England',0,'Base'],[5,'Cole Palmer','England',0,'Base'],[6,'Marcus Rashford','England',0,'Base'],[7,'Phil Foden','England',0,'Base'],[8,'Reece James','England',0,'Base'],[9,'Morgan Rogers','England',0,'Base'],[10,'Marc Guéhi','England',0,'Base'],[11,'Jordan Pickford','England',0,'Base'],[12,'Bukayo Saka','England',0,'Base'],[13,'Anthony Gordon','England',0,'Base'],[14,'Noni Madueke','England',0,'Base'],[15,'Eberechi Eze','England',0,'Base'],[16,'Elliot Anderson','England',0,'Base'],[17,'Kobbie Mainoo','England',0,'Base'],[18,'Ollie Watkins','England',0,'Base'],[19,"Nico O'Reilly",'England',0,'Base'],[20,'John Stones','England',0,'Base']
  ];
  catalog.checklists['panini-intl-france-2026'] = [
    [1,'Kylian Mbappé','France',0,'Base'],[2,'Mike Maignan','France',0,'Base'],[3,'Theo Hernández','France',0,'Base'],[4,'Marcus Thuram','France',0,'Base'],[5,'Manu Koné','France',0,'Base'],[6,'Warren Zaïre-Emery','France',0,'Base'],[7,'Michael Olise','France',0,'Base'],[8,'William Saliba','France',0,'Base'],[9,'Aurélien Tchouaméni','France',0,'Base'],[10,'Eduardo Camavinga','France',0,'Base'],[11,'Hugo Ekitike','France',0,'Base'],[12,'Dayot Upamecano','France',0,'Base'],[13,'Rayan Cherki','France',0,'Base'],[14,'Adrien Rabiot','France',0,'Base'],[15,'Ousmane Dembélé','France',0,'Base'],[16,'Désiré Doué','France',0,'Base'],[17,'Ibrahima Konaté','France',0,'Base'],[18,'Jules Koundé','France',0,'Base'],[19,'Bradley Barcola','France',0,'Base'],[20,"N'Golo Kanté",'France',0,'Base']
  ];
  catalog.checklists['panini-intl-germany-2026'] = [
    [1,'Joshua Kimmich','Germany',0,'Base'],[2,'Antonio Rüdiger','Germany',0,'Base'],[3,'Jonathan Tah','Germany',0,'Base'],[4,'David Raum','Germany',0,'Base'],[5,'Nick Woltemade','Germany',0,'Base'],[6,'Alexander Nübel','Germany',0,'Base'],[7,'Kai Havertz','Germany',0,'Base'],[8,'Ridle Baku','Germany',0,'Base'],[9,'Maximilian Mittelstädt','Germany',0,'Base'],[10,'Jamal Musiala','Germany',0,'Base'],[11,'Nico Schlotterbeck','Germany',0,'Base'],[12,'Waldemar Anton','Germany',0,'Base'],[13,'Leon Goretzka','Germany',0,'Base'],[14,'Deniz Undav','Germany',0,'Base'],[15,'Oliver Baumann','Germany',0,'Base'],[16,'Jamie Leweling','Germany',0,'Base'],[17,'Florian Wirtz','Germany',0,'Base'],[18,'Serge Gnabry','Germany',0,'Base'],[19,'Leroy Sané','Germany',0,'Base'],[20,'Karim Adeyemi','Germany',0,'Base']
  ];
  catalog.checklists['panini-intl-mexico-2026'] = [
    [1,'Raúl Jiménez','Mexico',0,'Base'],[2,'Obed Vargas','Mexico',0,'Base'],[3,'Marcel Ruiz','Mexico',0,'Base'],[4,'Roberto Alvarado','Mexico',0,'Base'],[5,'Edson Álvarez','Mexico',0,'Base'],[6,'César Montes','Mexico',0,'Base'],[7,'Erick Sánchez','Mexico',0,'Base'],[8,'Santiago Giménez','Mexico',0,'Base'],[9,'Hirving Lozano','Mexico',0,'Base'],[10,'Armando González','Mexico',0,'Base'],[11,'Gilberto Mora','Mexico',0,'Base'],[12,'Luis Malagón','Mexico',0,'Base'],[13,'Orbelín Pineda','Mexico',0,'Base'],[14,'Everardo López','Mexico',0,'Base'],[15,'Jesús Gallardo','Mexico',0,'Base'],[16,'Richard Ledezma','Mexico',0,'Base'],[17,'Germán Berterame','Mexico',0,'Base'],[18,'Johan Vásquez','Mexico',0,'Base'],[19,'Erik Lira','Mexico',0,'Base'],[20,'Raúl Rangel','Mexico',0,'Base']
  ];

  catalog.checklists['topps-barcelona-collector-tin-2025-26'] = [
    [1,'Joan García','FC Barcelona',0,'First Team'],[2,'Cubarsí','FC Barcelona',0,'First Team'],[3,'R. Araújo','FC Barcelona',0,'First Team'],[4,'Koundé','FC Barcelona',0,'First Team'],[5,'Balde','FC Barcelona',0,'First Team'],[6,'Guille Fernández','FC Barcelona',1,'First Team'],[7,'Dro','FC Barcelona',1,'First Team'],[8,'Olmo','FC Barcelona',0,'First Team'],[9,'Gavi','FC Barcelona',0,'First Team'],[10,'Pedri','FC Barcelona',0,'First Team'],[11,'F. de Jong','FC Barcelona',0,'First Team'],[12,'Fermín','FC Barcelona',0,'First Team'],[13,'Quim Junyent','FC Barcelona',1,'First Team'],[14,'Dani Rodríguez','FC Barcelona',1,'First Team'],[15,'Roony Bardghji','FC Barcelona',0,'First Team'],[16,'Marcus Rashford','FC Barcelona',0,'First Team'],[17,'Ferran','FC Barcelona',0,'First Team'],[18,'Raphinha','FC Barcelona',0,'First Team'],[19,'Lamine Yamal','FC Barcelona',0,'First Team'],[20,'Lewandowski','FC Barcelona',0,'First Team'],
    [21,'Alexia','FC Barcelona Femení',0,'Name in Lights'],[22,'A. Iniesta','FC Barcelona',0,'Name in Lights'],[23,'Xavi','FC Barcelona',0,'Name in Lights'],[24,'Raphinha','FC Barcelona',0,'Name in Lights'],[25,'Lamine Yamal','FC Barcelona',0,'Name in Lights'],[26,'Lewandowski','FC Barcelona',0,'Name in Lights'],[27,'Messi','FC Barcelona',0,'Name in Lights'],[28,'Ronaldinho','FC Barcelona',0,'Name in Lights'],[29,'Thierry Henry','FC Barcelona',0,'Name in Lights'],[30,'Luis Suárez','FC Barcelona',0,'Name in Lights'],
    ['GV-1','ter Stegen','FC Barcelona',0,'Gold Vault Limited Edition'],['GV-2','Alexia','FC Barcelona Femení',0,'Gold Vault Limited Edition'],['GV-3','Aitana','FC Barcelona Femení',0,'Gold Vault Limited Edition'],['GV-4','Raphinha','FC Barcelona',0,'Gold Vault Limited Edition'],['GV-5','Lamine Yamal','FC Barcelona',0,'Gold Vault Limited Edition'],['GV-6','Messi','FC Barcelona',0,'Gold Vault Limited Edition'],['GV-7','Ronaldinho','FC Barcelona',0,'Gold Vault Limited Edition'],['GV-8','Neymar Jr','FC Barcelona',0,'Gold Vault Limited Edition'],['GV-9','Ronaldo','FC Barcelona',0,'Gold Vault Limited Edition'],['GV-10',"Samuel Eto'o",'FC Barcelona',0,'Gold Vault Limited Edition'],
    ['AU-AB','Balde','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-AI','A. Iniesta','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-CF','Fàbregas','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-DO','Olmo','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-EA','Abidal','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-FT','Ferran','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-IR','Rakitić','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-JB','Belletti','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-JK','Koundé','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-LM','Lionel Messi','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-LY','Lamine Yamal','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-MC','Casadó','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-PE','Pedro','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-QJ','Quim Junyent','FC Barcelona',1,'Base Cards Autograph Variation'],['AU-RL','Lewandowski','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-RO','Ronaldinho','FC Barcelona',0,'Base Cards Autograph Variation'],['AU-TH','Thierry Henry','FC Barcelona',0,'Base Cards Autograph Variation']
  ];

  catalog.checklists['topps-man-city-collector-tin-2026-27'] = [
    [1,'Rayan Aït-Nouri','Manchester City',0,'First Team'],[2,'Rúben Dias','Manchester City',0,'First Team'],[3,'Joško Gvardiol','Manchester City',0,'First Team'],[4,'Abdukodir Khusanov','Manchester City',0,'First Team'],[5,'Marc Guéhi','Manchester City',0,'First Team'],[6,'Floyd Samba','Manchester City',1,'First Team'],[7,'Rayan Cherki','Manchester City',0,'First Team'],[8,'Jérémy Doku','Manchester City',0,'First Team'],[9,'Phil Foden','Manchester City',0,'First Team'],[10,'Rodrigo','Manchester City',0,'First Team'],[11,'Matheus Nunes','Manchester City',0,'First Team'],[12,'Tijjani Reijnders','Manchester City',0,'First Team'],[13,"Nico O'Reilly",'Manchester City',0,'First Team'],[14,'Savinho','Manchester City',0,'First Team'],[15,'Nico González','Manchester City',0,'First Team'],[16,'Charlie Gray','Manchester City',1,'First Team'],[17,'Erling Haaland','Manchester City',0,'First Team'],[18,'Ryan McAidoo','Manchester City',1,'First Team'],[19,'Antoine Semenyo','Manchester City',0,'First Team'],[20,'Omar Marmoush','Manchester City',0,'First Team'],[21,'Jade Rose','Manchester City Women',1,'First Team'],[22,'Laura Blindkilde Brown','Manchester City Women',0,'First Team'],[23,'Khadija Shaw','Manchester City Women',0,'First Team'],[24,'Iman Beney','Manchester City Women',1,'First Team'],
    [25,'Erling Haaland','Manchester City',0,'For The Badge'],[26,'Fernandinho','Manchester City',0,'For The Badge'],[27,'Kyle Walker','Manchester City',0,'For The Badge'],[28,'Phil Foden','Manchester City',0,'For The Badge'],[29,'David Silva','Manchester City',0,'For The Badge'],
    ['GV-1','Mario Balotelli','Manchester City',0,'Gold Vault Limited Edition'],['GV-2','Carlos Tevez','Manchester City',0,'Gold Vault Limited Edition'],['GV-3','Kevin De Bruyne','Manchester City',0,'Gold Vault Limited Edition'],['GV-4','Sergio Agüero','Manchester City',0,'Gold Vault Limited Edition'],['GV-5','Yaya Touré','Manchester City',0,'Gold Vault Limited Edition'],['GV-6','Roberto Mancini','Manchester City',0,'Gold Vault Limited Edition'],['GV-7','Riyad Mahrez','Manchester City',0,'Gold Vault Limited Edition'],['GV-8','Erling Haaland','Manchester City',0,'Gold Vault Limited Edition'],['GV-9','Rodrigo','Manchester City',0,'Gold Vault Limited Edition'],['GV-10','Rayan Cherki','Manchester City',0,'Gold Vault Limited Edition'],
    ['BC-AS','Antoine Semenyo','Manchester City',0,'Base Cards Autograph Variation'],['BC-EA','Emmanuel Adebayor','Manchester City',0,'Base Cards Autograph Variation'],['BC-EH','Erling Haaland','Manchester City',0,'Base Cards Autograph Variation'],['BC-EL','Elano','Manchester City',0,'Base Cards Autograph Variation'],['BC-GU','Marc Guéhi','Manchester City',0,'Base Cards Autograph Variation'],['BC-KB','Kevin De Bruyne','Manchester City',0,'Base Cards Autograph Variation'],['BC-LS','Leroy Sané','Manchester City',0,'Base Cards Autograph Variation'],['BC-TR','Tijjani Reijnders','Manchester City',0,'Base Cards Autograph Variation'],['BC-VM','Vivianne Miedema','Manchester City Women',0,'Base Cards Autograph Variation'],['BC-ZA','Pablo Zabaleta','Manchester City',0,'Base Cards Autograph Variation']
  ];

  window.CS_SET_META = window.CS_SET_META || {};
  Object.assign(window.CS_SET_META, {
    'panini-intl-england-2026': {parallels:['Holo','Pink /100','Purple /90','Orange /80','Red /49','Blue /25','Gold /10','Green /5','Black 1/1'],inserts:['Three Lions','Limitless','Master Class','New Sensations','Downtown','Victorious']},
    'panini-intl-france-2026': {parallels:['Holo','Orange /75','Red /40','Blue /25','Gold /10','Green /5','Black 1/1'],inserts:['Limitless','Master Class','New Sensations','Downtown','Victorious']},
    'panini-intl-germany-2026': {parallels:['Holo','Stars /299','Laser /249','Circles /199','Pink /149','Purple /125','Orange /99','Red /49','Blue /25','Gold /10','Green /5','Black 1/1'],inserts:['Adler','Limitless','Master Class','New Sensations','Downtown','Victorious']},
    'panini-intl-mexico-2026': {parallels:['Holo','Purple /90','Orange /65','Red /49','Blue /25','Gold /10','Green /5','Black 1/1'],inserts:['Aguila Real','Limitless','Master Class','New Sensations','Downtown','Victorious']}
  });
})();
