const CACHE='collectors-sports-v11c';
const IMAGE_CACHE='collectors-sports-images-v3';
const CORE=[
  './','./index.html','./styles.css?v=11c','./mobile-background.css?v=11c','./card-visuals.css?v=11c',
  './catalog.js?v=09a','./catalog-extra.js?v=09a','./catalog-imported.js?v=09a','./catalog-tennis.js?v=11c','./catalog-premier.js?v=09a',
  './catalog-owned.js?v=09a','./catalog-owned-batch2.js?v=09a','./catalog-owned-batch3.js?v=09a','./catalog-owned-batch4.js?v=11c','./catalog-owned-batch5.js?v=11c','./catalog-owned-batch6.js?v=11c','./catalog-owned-batch8.js?v=11c','./catalog-owned-batch9.js?v=11c',
  './catalog-runtime.js?v=09a','./catalog-now.js?v=11c','./catalog-now-extra.js?v=11c','./catalog-v11-fixes.js?v=11c','./catalog-now-sports-v11.js?v=11c',
  './catalog-images.js?v=11c','./catalog-images-official.js?v=09a','./catalog-images-extra.js?v=11c','./catalog-images-teamsets.js?v=09a','./catalog-images-cached.js?v=09a','./catalog-images-tennis.js?v=11c','./catalog-images-owned-batch4.js?v=11c','./catalog-images-owned-batch5.js?v=11c','./catalog-images-owned-batch6.js?v=11c','./catalog-images-owned-batch7.js?v=11c','./catalog-images-owned-batch8.js?v=11c','./catalog-images-owned-batch9.js?v=11c','./catalog-images-web-batch1.js?v=11c','./catalog-images-web-batch2.js?v=11c','./catalog-images-web-batch3.js?v=11c','./catalog-images-bulk.js?v=11c','./catalog-images-owned-exact-v11.js?v=11c',
  './card-visuals.js?v=11c','./app-v09-data-guard.js?v=11c','./market-seed.js?v=09a','./app-v05.js?v=11c','./app-v06-addon.js?v=11c','./app-v06-polish.js?v=09a','./app-v06-fix.js?v=09a','./pricing-engine.js?v=09a','./app-v08-image-guard.js?v=11c','./app-v08-catalog.js?v=09a','./app-v10-autocomplete.js?v=11c','./app-v11-home-search.js?v=11c','./app-v11-now-ui.js?v=11c','./app-v10-image-audit.js?v=11c','./inventory-photos.js?v=11c','./manifest.webmanifest?v=11c','./icon.svg?v=11c'
];
async function safeCachePut(cache,request,response){try{await cache.put(request,response);}catch(error){console.warn('Cache write skipped:',request.url||request,error);}}
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil(caches.open(CACHE).then(async cache=>{await cache.add('./index.html');await Promise.allSettled(CORE.filter(url=>url!=='./index.html').map(url=>cache.add(url)));}));});
self.addEventListener('activate',event=>{event.waitUntil(Promise.all([self.clients.claim(),caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE&&k!==IMAGE_CACHE).map(k=>caches.delete(k))))]));});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin===self.location.origin){event.respondWith(fetch(event.request).then(response=>{if(response&&response.ok){const copy=response.clone();event.waitUntil(caches.open(CACHE).then(cache=>safeCachePut(cache,event.request,copy)));}return response;}).catch(()=>caches.match(event.request)));return;}const imageHost=['images.topps.com','hobbyscan-images-prod.s3.us-east-2.amazonaws.com','i.ebayimg.com','http2.mlstatic.com','m.media-amazon.com','images-na.ssl-images-amazon.com'].includes(url.hostname);if(imageHost){event.respondWith(caches.open(IMAGE_CACHE).then(async cache=>{const cached=await cache.match(event.request);try{const response=await fetch(event.request);if(response&&(response.ok||response.type==='opaque'))event.waitUntil(safeCachePut(cache,event.request,response.clone()));return response;}catch(error){if(cached)return cached;throw error;}}));return;}event.respondWith(fetch(event.request).catch(()=>caches.match(event.request)));});
