from __future__ import annotations

import base64
import io
import re
import urllib.request
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'catalog-images.js'
OUTPUT = ROOT / 'catalog-images-cached.js'

CARD_RE = re.compile(
    r"'(?P<key>[^']+\|[^']+)':\s*\{(?P<body>.*?)\n\s*\}",
    re.S,
)
FRONT_RE = re.compile(r"front:\s*'([^']+)'", re.S)
KIND_RE = re.compile(r"kind:\s*'([^']+)'", re.S)


def fetch(url: str) -> bytes:
    req = urllib.request.Request(
        url,
        headers={
            'User-Agent': 'Mozilla/5.0 (Collectors Sports image cache; contact via GitHub repo)',
            'Accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8',
        },
    )
    with urllib.request.urlopen(req, timeout=25) as response:
        return response.read()


def compress(raw: bytes) -> str:
    with Image.open(io.BytesIO(raw)) as image:
        image = image.convert('RGB')
        image.thumbnail((720, 1000), Image.Resampling.LANCZOS)
        out = io.BytesIO()
        image.save(out, format='JPEG', quality=78, optimize=True, progressive=True)
        payload = base64.b64encode(out.getvalue()).decode('ascii')
        return f'data:image/jpeg;base64,{payload}'


def existing_cache() -> dict[str, str]:
    if not OUTPUT.exists():
        return {}
    text = OUTPUT.read_text(encoding='utf-8')
    pairs = re.findall(r"'([^']+\|[^']+)':\s*'([^']+)'", text)
    return dict(pairs)


def main() -> None:
    text = SOURCE.read_text(encoding='utf-8')
    cached = existing_cache()
    found = 0
    updated = 0

    for match in CARD_RE.finditer(text):
        key = match.group('key')
        body = match.group('body')
        kind_match = KIND_RE.search(body)
        front_match = FRONT_RE.search(body)
        if not kind_match or not front_match or kind_match.group(1) != 'exact':
            continue
        found += 1
        url = front_match.group(1)
        try:
            raw = fetch(url)
            cached[key] = compress(raw)
            updated += 1
            print(f'cached {key}')
        except Exception as exc:
            print(f'warning: could not cache {key}: {exc}')

    lines = [
        '// Generated by tools/cache_exact_images.py.',
        '// Small same-origin copies of exact card images so the app does not depend on hotlinking.',
        'window.CS_IMAGE_CACHE = {',
    ]
    for key in sorted(cached):
        lines.append(f"  {key!r}: {cached[key]!r},")
    lines.append('};')
    OUTPUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'wrote {OUTPUT.name}: {len(cached)} cached exact images ({updated}/{found} refreshed)')


if __name__ == '__main__':
    main()
