#!/usr/bin/env python3
"""Bulk exact-front importer for expanded TCDB product identities.

Groups catalog identities by their source TCDB SID (recorded in row[8] by
sync_tcdb_products.py), then reuses the conservative importer to resolve/check the
exact card page and cache a same-origin WebP front. Newly accepted entries are
explicitly marked exactVerified=true for the strict UI.
"""
from __future__ import annotations

import json
import os
import sys
import time
from collections import defaultdict
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'tools'))
import import_bulk_card_images as legacy

TARGETS=ROOT/'data'/'image-targets-runtime.json'
MANIFEST=ROOT/'data'/'bulk-image-manifest.json'
REPORT=ROOT/'data'/'bulk-image-report.json'
MAX_NEW=int(os.getenv('IMAGE_IMPORT_MAX_NEW','2500'))


def load(path,default):
    try:return json.loads(path.read_text(encoding='utf-8'))
    except Exception:return default


def main():
    targets=load(TARGETS,{})
    manifest=load(MANIFEST,{})
    before=len(manifest)
    remaining=MAX_NEW
    report={'provider':'TCDB expanded exact-front resolver','startedAt':time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime()),'maxNew':MAX_NEW,'collections':{}}
    for cid,payload in targets.items():
        if remaining<=0:break
        groups=defaultdict(list)
        source=payload.get('source') or {}
        root_sid=source.get('sid')
        for row in payload.get('rows') or []:
            sid=str(row.get('sourceSid') or root_sid or '').strip()
            if sid:groups[sid].append(row)
        cstats={'sourceSets':len(groups),'newExact':0,'sets':{}}
        for sid,rows in groups.items():
            if remaining<=0:break
            set_name=next((r.get('tcdbSetName') for r in rows if r.get('tcdbSetName')),None) or source.get('setName') or cid
            p={'source':{'provider':'tcdb','sid':int(sid),'setName':set_name,'allowedSubsets':[]},'rows':rows}
            try:
                count,stats=legacy.import_tcdb(cid,p,manifest,set(),remaining)
                if count:
                    # Strict UI requires explicit verification. The legacy importer already
                    # validates set + number + player and caches the selected front locally.
                    keys={legacy.row_key(cid,r) for r in rows}
                    for k in keys:
                        if k in manifest:
                            manifest[k]['exactVerified']=True
                            manifest[k]['verificationMethod']='TCDB exact card page + identity match + cached front'
                remaining-=count;cstats['newExact']+=count;cstats['sets'][sid]=stats
                legacy.write_manifest(manifest);legacy.write_js(manifest)
            except Exception as exc:
                cstats['sets'][sid]={'fatalError':str(exc)}
        report['collections'][cid]=cstats
    # Migrate any pre-existing strict TCDB manifest entries generated by this resolver.
    for item in manifest.values():
        if item.get('source')=='Trading Card Database' and item.get('kind')=='exact':
            item['exactVerified']=True
            item.setdefault('verificationMethod','TCDB exact card page + identity match + cached front')
    legacy.write_manifest(manifest);legacy.write_js(manifest)
    report['finishedAt']=time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime())
    report['manifestExactFronts']=len(manifest);report['newExactFrontsThisRun']=len(manifest)-before
    REPORT.parent.mkdir(parents=True,exist_ok=True);REPORT.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(f"TCDB expanded exact fronts: +{report['newExactFrontsThisRun']} / {len(manifest)} total")

if __name__=='__main__':main()
