#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path

import requests
from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'catalog-fc-tins-expanded.js'
REPORT = ROOT / 'data' / 'fc-tins-sync-report.json'
URL = 'https://www.halloflists.com/products/2026-27-topps-fc-collector-tin'
UA = {'User-Agent': 'CollectorsSports/1.0 (+catalog sync)'}
TARGETS = [
    ('topps-chelsea-collector-tin-2026-27', 'Chelsea Collector Tin 26/27', 'Chelsea'),
    ('topps-man-city-collector-tin-2026-27', 'Man City Collector Tin 26/27', 'Manchester City'),
    ('topps-man-utd-collector-tin-2026-27', 'Man United Collector Tin 26/27', 'Manchester United'),
]


def clean(value):
    return re.sub(r'\s+', ' ', str(value or '')).strip()


def write_report(status, *, reason=None, total_rows=0, collections=None):
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        'source': URL,
        'status': status,
        'totalRows': total_rows,
        'collections': collections or [],
        'preservedExistingCatalog': status != 'ok',
    }
    if reason:
        payload['reason'] = reason
    REPORT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


def parse_rows(html):
    soup = BeautifulSoup(html, 'html.parser')
    heading = None
    for tag in soup.find_all(['h2', 'h3', 'p']):
        text = clean(tag.get_text(' ', strip=True)).lower()
        if 'checklist' in text and ('text index' in text or 'card list' in text):
            heading = tag
            break

    if heading is None:
        return []

    rows = []
    subset = ''
    for el in heading.find_all_next(['h3', 'h4', 'li']):
        if el.name in {'h3', 'h4'}:
            raw = clean(el.get_text(' ', strip=True))
            match = re.match(r'^(.*?)\s*\((\d+)\)\s*$', raw)
            subset = clean(match.group(1)) if match else raw
            continue
        if el.name != 'li' or not subset:
            continue
        text = clean(el.get_text(' ', strip=True))
        match = re.match(r'^#([^\s]+)\s+(.+)$', text)
        if not match:
            continue
        number, player = match.groups()
        lower_subset = subset.lower()
        category = 'autograph' if 'autograph' in lower_subset else ('insert' if 'gold vault' in lower_subset else 'base')
        flags = ['AUTO'] if category == 'autograph' else 0
        rows.append([number, player, '', flags, subset, category, subset, ''])
        if len(rows) >= 147:
            break
    return rows


def main():
    try:
        response = requests.get(URL, headers=UA, timeout=35)
        response.raise_for_status()
        rows = parse_rows(response.text)
    except Exception as exc:
        reason = f'fetch failed: {type(exc).__name__}: {exc}'
        write_report('skipped', reason=reason)
        print(f'FC Collector Tins skipped; preserving existing catalog: {reason}', flush=True)
        return 0

    if len(rows) != 147:
        reason = f'source layout changed; expected 147 cards, parsed {len(rows)}'
        write_report('skipped', reason=reason, total_rows=len(rows))
        print(f'FC Collector Tins skipped; preserving existing catalog: {reason}', flush=True)
        return 0

    payload = {}
    report = []
    for idx, (cid, short, club) in enumerate(TARGETS):
        chunk = [list(x) for x in rows[idx * 49:(idx + 1) * 49]]
        for row in chunk:
            row[2] = club
            subset_slug = re.sub(r'[^a-z0-9]+', '-', row[4].lower()).strip('-')
            row[7] = f'hol:fc-tin:{cid}:{subset_slug}:{row[0]}'
        payload[cid] = {
            'collection': {
                'id': cid,
                'sport': 'Soccer',
                'manufacturer': 'Topps',
                'year': '2026/27',
                'name': f'Topps {club} Collector Tin 2026/27',
                'shortName': short,
                'sourceUrl': URL,
                'coverage': 'full-checklist',
                'entryIdentity': True,
                'expandedCount': 49,
            },
            'rows': chunk,
        }
        report.append({'collectionId': cid, 'club': club, 'rows': len(chunk), 'base': 29, 'autographs': 10, 'goldVault': 10})

    packed = json.dumps(payload, ensure_ascii=False, separators=(',', ':'))
    js = f"""// Generated by tools/sync_fc_collector_tins.py.\n(() => {{const catalog=window.CS_CATALOG;if(!catalog)return;catalog.checklists=catalog.checklists||{{}};const payload={packed};const key=r=>`${{String(r?.[0]??'').toLowerCase()}}|${{String(r?.[1]??'').toLowerCase()}}|${{String(r?.[4]??'').toLowerCase()}}`;for(const [id,p] of Object.entries(payload)){{let c=catalog.collections.find(x=>x.id===id);if(c)Object.assign(c,p.collection);else{{c={{...p.collection}};catalog.collections.push(c);}}const old=catalog.checklists[id]||[];const seen=new Set(old.map(key));const merged=[...old];for(const row of p.rows){{const k=key(row);if(!seen.has(k)){{merged.push(row);seen.add(k);}}}}catalog.checklists[id]=merged;c.expandedCount=merged.length;c.entryIdentity=true;}}}})();\n"""
    OUT.write_text(js, encoding='utf-8')
    write_report('ok', total_rows=147, collections=report)
    print('FC Collector Tins: 147 cards split into Chelsea, Manchester City and Manchester United', flush=True)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
