#!/usr/bin/env python3
"""Generate catalog-premier.js from Topps' official Premier League 2025/26 PDF."""
from __future__ import annotations

import io
import json
import re
import urllib.request
from pathlib import Path

from pypdf import PdfReader

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "catalog-premier.js"
COLLECTION_ID = "topps-premier-league-2025-26"
URL = "https://cdn.shopify.com/s/files/1/0739/2015/1805/files/Topps_Premier_League_2026_Hobby_Checklist.pdf?v=1756731624"

TEAMS = sorted([
    "Brighton & Hove Albion", "Wolverhampton Wanderers", "Nottingham Forest",
    "Manchester United", "Manchester City", "Newcastle United", "Tottenham Hotspur",
    "AFC Bournemouth", "Crystal Palace", "West Ham United", "Aston Villa",
    "Liverpool FC", "Burnley FC", "Leeds United", "Sunderland", "Brentford",
    "Chelsea", "Everton", "Fulham", "Arsenal",
], key=len, reverse=True)


def clean(value: str) -> str:
    return re.sub(r"\s+", " ", str(value).replace("®", "").replace("™", "")).strip()


def fetch() -> bytes:
    req = urllib.request.Request(URL, headers={"User-Agent": "CollectorsSportsCatalog/1.0"})
    with urllib.request.urlopen(req, timeout=90) as response:
        return response.read()


def text_lines(data: bytes) -> list[str]:
    reader = PdfReader(io.BytesIO(data))
    out: list[str] = []
    for page in reader.pages:
        text = page.extract_text() or ""
        out.extend(clean(line) for line in text.splitlines() if clean(line))
    return out


def numbered_segments(line: str) -> list[str]:
    starts = [m.start() for m in re.finditer(r"(?<!\d)(?=\d{1,3}\s+)", line)]
    if not starts:
        return []
    segments: list[str] = []
    for i, start in enumerate(starts):
        end = starts[i + 1] if i + 1 < len(starts) else len(line)
        segment = clean(line[start:end])
        if re.match(r"^\d{1,3}\s+", segment):
            segments.append(segment)
    return segments


def parse(data: bytes) -> list[list]:
    rows: dict[int, list] = {}
    for line in text_lines(data):
        if line == "PRO PARTNERSHIPS":
            break
        for segment in numbered_segments(line):
            match = re.match(r"^(\d{1,3})\s+(.+)$", segment)
            if not match:
                continue
            number = int(match.group(1))
            if not 1 <= number <= 360:
                continue
            rest = clean(match.group(2))
            found = None
            for team in TEAMS:
                idx = rest.find(team)
                if idx >= 0:
                    found = (idx, team)
                    break
            if not found:
                continue
            idx, team = found
            subject = clean(rest[:idx]) or team
            rows.setdefault(number, [number, subject, team, 0])
    missing = [n for n in range(1, 361) if n not in rows]
    if len(rows) < 350:
        raise RuntimeError(f"Premier League parser extracted only {len(rows)}/360 cards; missing {missing[:20]}")
    if missing:
        raise RuntimeError(f"Premier League parser missing numbered cards: {missing}")
    return [rows[n] for n in range(1, 361)]


def render(rows: list[list]) -> str:
    payload = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
    return f'''// Generated by tools/sync_premier.py from Topps' official checklist.\n// Do not edit by hand.\n(() => {{\n  const catalog = window.CS_CATALOG;\n  if (!catalog) return;\n  const rows = {payload};\n  catalog.checklists[{json.dumps(COLLECTION_ID)}] = rows;\n  const collection = catalog.collections.find(c => c.id === {json.dumps(COLLECTION_ID)});\n  if (collection) {{ collection.coverage = 'base-complete'; collection.baseCount = rows.length; }}\n}})();\n'''


def main() -> int:
    rows = parse(fetch())
    OUTPUT.write_text(render(rows), encoding="utf-8")
    print(f"Wrote {OUTPUT.name} with {len(rows)} numbered Premier League cards")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
