#!/usr/bin/env python3
from __future__ import annotations
import json,re
from pathlib import Path
import requests
from bs4 import BeautifulSoup

ROOT=Path(__file__).resolve().parents[1]
CONFIG=ROOT/'owned_priority_sources.json'
OUT=ROOT/'catalog-owned-priority-expanded.js'
REPORT=ROOT/'data'/'owned-priority-sync-report.json'
UA={'User-Agent':'CollectorsSports/1.0 (+catalog sync)'}


def clean(v): return re.sub(r'\s+',' ',str(v or '')).strip()

def category(subset):
    s=subset.lower()
    if 'autograph' in s or re.search(r'\bauto\b',s): return 'autograph'
    if any(x in s for x in ('memorabilia','relic','material','patch','swatch')): return 'relic'
    if s.startswith('base'): return 'base'
    return 'insert'

def parse_card_line(line):
    line=clean(line).replace('\xa0',' ')
    if not line:return None
    # common checklist forms: 1 Player, Team  OR  1 Player - Team  OR #1 Player
    m=re.match(r'^#?([A-Za-z0-9][A-Za-z0-9./_-]{0,24})\s+(.+?)\s+-\s+(.+?)(?:\s+/\d+|\s+1/1)?$',line)
    if m:return m.group(1),clean(m.group(2)),clean(m.group(3))
    m=re.match(r'^#?([A-Za-z0-9][A-Za-z0-9./_-]{0,24})\s+([^,]{2,80}),\s*(.+?)(?:\s+/\d+|\s+1/1)?$',line)
    if m:return m.group(1),clean(m.group(2)),clean(m.group(3))
    m=re.match(r'^#?([A-Za-z0-9][A-Za-z0-9./_-]{0,24})\s+(.{2,100})$',line)
    if m and not re.search(r'^(cards?|parallels?|boxes?|packs?)\b',m.group(2),re.I):
        return m.group(1),clean(m.group(2)),''
    return None

def parse_sections(html):
    soup=BeautifulSoup(html,'html.parser'); rows=[]; seen=set(); sections={}
    headings=soup.find_all(['h2','h3','h4'])
    for h in headings:
        title=clean(h.get_text(' ',strip=True))
        if not title or re.search(r'team set lists?|box info|at a glance|shop for|overview|rundown|details',title,re.I): continue
        if not re.search(r'base|insert|autograph|signature|memorabilia|relic|material|checklist|vault|lights|baller|first team|toast|apple|golden',title,re.I): continue
        subset=re.sub(r'\s+Checklist.*$','',title,flags=re.I).strip()
        count=0
        node=h.find_next_sibling()
        while node:
            if getattr(node,'name',None) in ('h2','h3','h4'): break
            text=node.get_text('\n',strip=True) if hasattr(node,'get_text') else ''
            for raw in text.splitlines():
                parsed=parse_card_line(raw)
                if not parsed: continue
                number,player,team=parsed
                key=(number.lower(),player.lower(),subset.lower())
                if key in seen: continue
                seen.add(key)
                cat=category(subset); flags=[]
                if re.search(r'\bRC\b|rookie',raw,re.I): flags.append('RC')
                if cat=='autograph': flags.append('AUTO')
                if cat=='relic': flags.append('RELIC')
                rows.append([number,re.sub(r'\s+RC\b','',player,flags=re.I).strip(),team,flags or 0,subset,cat,subset,''])
                count+=1
            node=node.find_next_sibling()
        if count: sections[subset]=count
    return rows,sections

def parse_product(cfg):
    r=requests.get(cfg['url'],headers=UA,timeout=40); r.raise_for_status()
    rows,sections=parse_sections(r.text)
    # Conservative failure: never replace/claim a full set when extraction is implausibly small.
    expected=int(cfg.get('expectedTotalCount') or cfg.get('expectedBaseCount') or 0)
    if expected and len(rows)<min(20,max(8,int(expected*0.15))):
        raise RuntimeError(f'only {len(rows)} rows parsed from expected source size {expected}')
    if not rows: raise RuntimeError('no checklist rows parsed')
    for row in rows:
        subset_slug=re.sub(r'[^a-z0-9]+','-',row[4].lower()).strip('-')
        row[7]=f"owned:{cfg['collectionId']}:{subset_slug}:{row[0]}"
    collection={'id':cfg['collectionId'],'sport':cfg['sport'],'manufacturer':cfg['manufacturer'],'year':cfg['year'],'name':cfg['name'],'shortName':cfg['shortName'],'sourceUrl':cfg['url'],'coverage':'owned-priority-published-checklist','entryIdentity':True,'expandedCount':len(rows)}
    return collection,rows,sections

def render(payload):
    packed=json.dumps(payload,ensure_ascii=False,separators=(',',':'))
    return f"""// Generated by tools/sync_owned_priority_sources.py.\n(() => {{const catalog=window.CS_CATALOG;if(!catalog)return;catalog.checklists=catalog.checklists||{{}};const payload={packed};const key=r=>`${{String(r?.[0]??'').toLowerCase()}}|${{String(r?.[1]??'').toLowerCase()}}|${{String(r?.[4]??'').toLowerCase()}}`;for(const [id,p] of Object.entries(payload)){{let c=catalog.collections.find(x=>x.id===id);if(c)Object.assign(c,p.collection);else{{c={{...p.collection}};catalog.collections.push(c);}}const old=catalog.checklists[id]||[];const seen=new Set(old.map(key));const merged=[...old];for(const r of p.rows){{const k=key(r);if(!seen.has(k)){{merged.push(r);seen.add(k);}}}}catalog.checklists[id]=merged;c.expandedCount=merged.length;c.entryIdentity=true;}}}})();\n"""

def main():
    cfg=json.loads(CONFIG.read_text(encoding='utf-8')); payload={}; reports=[]
    for p in cfg.get('products',[]):
        try:
            c,rows,sections=parse_product(p); payload[c['id']]={'collection':c,'rows':rows}; reports.append({'collectionId':c['id'],'rows':len(rows),'sections':sections,'status':'ok'}); print(f"{c['id']}: {len(rows)} rows",flush=True)
        except Exception as exc:
            reports.append({'collectionId':p.get('collectionId'),'rows':0,'status':'error','error':str(exc)}); print(f"{p.get('collectionId')}: skipped ({exc})",flush=True)
    OUT.write_text(render(payload),encoding='utf-8'); REPORT.parent.mkdir(parents=True,exist_ok=True); REPORT.write_text(json.dumps({'products':reports,'totalRows':sum(x.get('rows',0) for x in reports)},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

if __name__=='__main__': main()
