#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path

import requests
from bs4 import BeautifulSoup, Tag

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / 'checklistinsider_sources.json'
OUT = ROOT / 'catalog-checklistinsider-expanded.js'
REPORT = ROOT / 'data' / 'checklistinsider-sync-report.json'
UA = {'User-Agent':'CollectorsSports/1.0 (+catalog sync)'}

SKIP_HEADINGS = re.compile(r'team set|team checklist|parallel|box|odds|rundown|details', re.I)
AUTO = re.compile(r'autograph|signatures?|autos?\b', re.I)
RELIC = re.compile(r'relic|memorabilia|patch|swatch|materials?', re.I)


def clean(v):
    return re.sub(r'\s+',' ',str(v or '')).strip()


def category(subset):
    if AUTO.search(subset) and RELIC.search(subset): return 'auto-relic'
    if AUTO.search(subset): return 'autograph'
    if RELIC.search(subset): return 'relic'
    if re.search(r'rookie',subset,re.I): return 'rookie-insert'
    if re.search(r'^base(?:\s|$)',subset,re.I): return 'base'
    return 'insert'


def parse_line(line):
    line=clean(line).replace('\xa0',' ')
    if not line or line.lower().startswith(('parallels:', 'versions:', 'buy on ebay', 'all cards', 'cards.')): return None
    line=re.sub(r'^[•·]\s*','',line)
    # common format: 1 Player - Team OR CODE Player - Team /serial
    m=re.match(r'^([A-Za-z0-9][A-Za-z0-9./_-]{0,24})\s+(.+?)\s+-\s+(.+)$',line)
    if not m:
        # update/autograph lines can prefix another set name before the card number
        m=re.match(r'^.+?\s+-\s+([A-Za-z0-9][A-Za-z0-9./_-]{0,24})\s+(.+?)\s+-\s+(.+)$',line)
    if not m: return None
    number,player,team=m.groups()
    if number.lower() in {'base','cards','card','parallels'}: return None
    if len(player)<2 or len(team)<2: return None
    serial=''
    sm=re.search(r'\s+(/\d+|1/1)(?:\s.*)?$',team,re.I)
    if sm:
        serial=sm.group(1); team=team[:sm.start()].strip()
    player=re.sub(r'\s+RC\b','',player,flags=re.I).strip()
    return number.strip(),player,team,serial


def section_lines(heading: Tag):
    lines=[]
    node=heading.next_sibling
    while node:
        if isinstance(node,Tag) and node.name in ('h2','h3'):
            break
        if isinstance(node,Tag):
            text=node.get_text('\n',strip=True)
            lines.extend(x.strip() for x in text.splitlines() if x.strip())
        node=node.next_sibling
    return lines


def parse_product(cfg):
    r=requests.get(cfg['url'],headers=UA,timeout=35);r.raise_for_status()
    soup=BeautifulSoup(r.text,'html.parser')
    rows=[];seen=set();sections={}
    for h in soup.find_all('h3'):
        title=clean(h.get_text(' ',strip=True))
        if not re.search(r'Checklist$',title,re.I): continue
        if SKIP_HEADINGS.search(title): continue
        subset=re.sub(r'\s+Checklist$','',title,flags=re.I).strip()
        cat=category(subset)
        count=0
        for line in section_lines(h):
            parsed=parse_line(line)
            if not parsed: continue
            number,player,team,serial=parsed
            key=(number.lower(),player.lower(),subset.lower())
            if key in seen: continue
            seen.add(key)
            flags=[]
            if re.search(r'\bRC\b|rookie',line,re.I): flags.append('RC')
            if AUTO.search(subset): flags.append('AUTO')
            if RELIC.search(subset): flags.append('RELIC')
            variant=subset + (f' {serial}' if serial else '')
            rows.append([number,player,team,flags or 0,subset,cat,variant,f"ci:{cfg['collectionId']}:{re.sub(r'[^a-z0-9]+','-',subset.lower()).strip('-')}:{number}"])
            count+=1
        if count: sections[subset]=count
    if not rows: raise RuntimeError('no checklist rows parsed')
    collection={
      'id':cfg['collectionId'],'sport':cfg['sport'],'manufacturer':cfg['manufacturer'],'year':cfg['year'],
      'name':cfg['name'],'shortName':cfg['shortName'],'sourceUrl':cfg['url'],'coverage':'published-checklist-import',
      'entryIdentity':True,'expandedCount':len(rows)
    }
    return collection,rows,{'collectionId':cfg['collectionId'],'rows':len(rows),'sections':sections,'status':'ok'}


def render(payload):
    packed=json.dumps(payload,ensure_ascii=False,separators=(',',':'))
    return f"""// Generated by tools/sync_checklistinsider.py. Do not edit by hand.\n(() => {{const catalog=window.CS_CATALOG;if(!catalog)return;catalog.checklists=catalog.checklists||{{}};const payload={packed};const key=r=>`${{String(r?.[0]??'').toLowerCase()}}|${{String(r?.[1]??'').toLowerCase()}}|${{String(r?.[4]??'').toLowerCase()}}`;for(const [id,p] of Object.entries(payload)){{let c=catalog.collections.find(x=>x.id===id);if(c)Object.assign(c,p.collection);else{{c={{...p.collection}};catalog.collections.push(c);}}const old=catalog.checklists[id]||[];const seen=new Set(old.map(key));const merged=[...old];for(const r of p.rows){{const k=key(r);if(!seen.has(k)){{merged.push(r);seen.add(k);}}}}catalog.checklists[id]=merged;c.expandedCount=merged.length;c.entryIdentity=true;}}}})();\n"""


def main():
    cfg=json.loads(CONFIG.read_text(encoding='utf-8'));payload={};reports=[]
    for product in cfg.get('products',[]):
        try:
            collection,rows,report=parse_product(product);payload[collection['id']]={'collection':collection,'rows':rows};reports.append(report)
            print(f"{collection['id']}: {len(rows)} rows",flush=True)
        except Exception as exc:
            reports.append({'collectionId':product.get('collectionId'),'rows':0,'status':'error','error':str(exc)})
            print(f"{product.get('collectionId')}: skipped ({exc})",flush=True)
    OUT.write_text(render(payload),encoding='utf-8');REPORT.parent.mkdir(parents=True,exist_ok=True)
    REPORT.write_text(json.dumps({'products':reports,'totalRows':sum(int(x.get('rows') or 0) for x in reports)},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

if __name__=='__main__': main()
