#!/usr/bin/env python3
"""Build collection-level visual galleries from official Topps product pages.

This importer intentionally does NOT guess card-number matches. Product-page images are
stored as collection references unless a card has been curated separately in
catalog-images.js. That keeps visual confirmation honest while still giving every
supported collection a useful official gallery.
"""

from __future__ import annotations

import html
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path

OUT = Path('catalog-images-official.js')

SOURCES = {
    'topps-chrome-ucc-2025-26': 'https://www.topps.com/pages/topps-chrome-uefa-club-competitions',
    'topps-ucc-2025-26': 'https://www.topps.com/pages/uefa-club-competitions',
    'topps-chrome-premier-league-2026': 'https://www.topps.com/pages/topps-chrome-premier-league',
    'topps-pristine-premier-league-2025-26': 'https://www.topps.com/pages/topps-pristine-premier-league',
    'topps-chrome-sapphire-ucc-2025-26': 'https://www.topps.com/pages/topps-chrome-ucc-sapphire',
    'topps-chrome-baseball-2026': 'https://www.topps.com/pages/topps-chrome-baseball',
    'topps-chrome-football-2025': 'https://www.topps.com/pages/topps-chrome-football',
    'topps-signature-class-football-2025': 'https://www.topps.com/pages/signature-class-football',
    'topps-chrome-ufc-2026': 'https://www.topps.com/pages/topps-chrome-ufc',
    'topps-chrome-f1-2026': 'https://www.topps.com/pages/topps-chrome-formula-1',
    'topps-chrome-basketball-2025-26': 'https://www.topps.com/pages/topps-chrome-basketball',
    'topps-chrome-updates-basketball-2025-26': 'https://www.topps.com/pages/topps-chrome-updates-basketball',
    'topps-chrome-black-basketball-2025-26': 'https://www.topps.com/pages/topps-chrome-black-basketball',
}

IMAGE_RE = re.compile(r'https://images\.topps\.com/[^\"\'<>\s\\]+', re.I)
EXT_RE = re.compile(r'\.(?:jpg|jpeg|png|webp)(?:\?|$)', re.I)


def fetch(url: str) -> str:
    req = urllib.request.Request(
        url,
        headers={
            'User-Agent': 'Mozilla/5.0 CollectorsSportsCatalog/0.6',
            'Accept': 'text/html,application/xhtml+xml',
        },
    )
    with urllib.request.urlopen(req, timeout=30) as response:
        return response.read().decode('utf-8', errors='replace')


def clean_url(raw: str) -> str:
    value = html.unescape(raw).replace('\\u0026', '&').replace('\\/', '/')
    return value.rstrip('),]')


def filename_label(url: str) -> str:
    path = urllib.parse.urlparse(url).path
    name = urllib.parse.unquote(path.rsplit('/', 1)[-1])
    stem = re.sub(r'\.(jpg|jpeg|png|webp)$', '', name, flags=re.I)
    return stem.replace('_', ' ').strip()


def extract_images(page_html: str, limit: int = 12) -> list[dict[str, str]]:
    seen: set[str] = set()
    images: list[dict[str, str]] = []
    for raw in IMAGE_RE.findall(page_html):
        url = clean_url(raw)
        if not EXT_RE.search(url):
            continue
        # Strip common resizing parameters; the original asset is better for zoom.
        parsed = urllib.parse.urlsplit(url)
        url = urllib.parse.urlunsplit((parsed.scheme, parsed.netloc, parsed.path, '', ''))
        if url in seen:
            continue
        seen.add(url)
        images.append({'url': url, 'label': filename_label(url)})
        if len(images) >= limit:
            break
    return images


def build() -> dict[str, dict]:
    result: dict[str, dict] = {}
    for collection_id, source_page in SOURCES.items():
        print(f'Fetching images for {collection_id}')
        try:
            page = fetch(source_page)
            gallery = extract_images(page)
        except Exception as exc:
            print(f'  ! skipped: {exc}')
            continue
        if not gallery:
            print('  ! no images found')
            continue
        print(f'  -> {len(gallery)} images')
        result[collection_id] = {
            'source': 'Topps',
            'sourcePage': source_page,
            'kind': 'collection',
            'label': 'Galería oficial Topps',
            'cover': gallery[0]['url'],
            'gallery': gallery,
        }
    return result


def write_js(data: dict[str, dict]) -> None:
    payload = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    js = f"""// Generated by tools/sync_official_images.py from official Topps product pages.\n// Collection-level references only; exact card mappings live in catalog-images.js.\n(() => {{\n  const root = window.CS_IMAGE_CATALOG = window.CS_IMAGE_CATALOG || {{collections:{{}},cards:{{}}}};\n  root.collections = root.collections || {{}};\n  root.cards = root.cards || {{}};\n  const generated = {payload};\n  Object.entries(generated).forEach(([id, data]) => {{\n    root.collections[id] = {{...(root.collections[id] || {{}}), ...data}};\n  }});\n}})();\n"""
    OUT.write_text(js, encoding='utf-8')
    print(f'Wrote {OUT} with {len(data)} collection galleries')


if __name__ == '__main__':
    write_js(build())
